#!/usr/bin/perl

use strict;
use warnings;

use feature qw(say);

if (not defined $ARGV[0]) {
  die "pack <path-to-directory-for-tar-gz>";
}

my $dir = $ARGV[0];
if (!(-e $dir)) {
  die "No such directory";
}

my $name = "";
if ($dir =~ /\//) {
  ($name) = ($dir =~ m/.*\/(.+)/);
} else {
  $name = $dir;
}

system("tar -czvf $name.tar.gz $dir");
