#!/usr/bin/perl

use strict;
use warnings;

use feature qw(say);

if (not defined $ARGV[0]) {
  die "unpack <path-to-tar-gz>";
}

my $arch = $ARGV[0];
if (!(-e $arch)) {
  die "No such directory";
}

if ($arch !~ /^.*\.tar\.gz$/) {
  die "*.tar.gz only";
}

system("tar -xzf $arch");
